---
title: "paper figures"
output: html_document
date: "2025-07-13"
---

```{r}

library(tidyverse)
library(ggpubr)
library(cowplot)
library(ape)
library(ggtree)      # For tree visualization and gheatmap
library(pheatmap)

#load functions
source('./functions.R')

```

## microbial profile

```{r}

profiler.fam(metaphlan = "../data/clean/speciesAbund.txt",
             mapfile = "../data/clean/mapfile.txt")
ggsave("../figs/Species_profile.pdf", width = 18, height = 14, units = "cm")

```

## microbial diversity

```{r}

vis.shannon(Shannon = "../data/clean/diversity_shannon.txt",
            Mapfile = "../data/clean/mapfile.txt")
ggsave("../figs/diversity_shannon.pdf", width = 12, 
       height = 10, units = "cm")

```

## microbial distance

```{r}

vis.pairBray(Paired_bray = "../data/clean/paired_bray.txt",
             Mapfile = "../data/clean/mapfile.txt")
ggsave("../figs/diversity_pairdBray.pdf", width = 15, 
       height = 10, units = "cm")

```
## assembly quality check

```{r}

vis.contigs()
ggsave("../figs/cumulative_contigs.pdf", width = 12, 
       height = 10, units = "cm")

```

```{r}

vis.bins()
ggsave("../figs/bins_quality.pdf", width = 18, 
       height = 8, units = "cm")

```


## Count number of colonization per feature

```{r}

CountFig(ftype = "Bin")
ggsave("../figs/Bin_CF.pdf",
       width = 16, height = 10, 
       units = "cm")

```


```{r}

CountFig(ftype = "MAG")
ggsave("../figs/MAG_CF.pdf",
       width = 16, height = 10, 
       units = "cm")

```


```{r}

CountFig(ftype = "Species")
ggsave("../figs/Species_CF.pdf",
       width = 16, height = 10, 
       units = "cm")

```


```{r}

CountFig(ftype = "Gene")
ggsave("../figs/Gene_CF.pdf",
       width = 16, height = 10, 
       units = "cm")

```


## compare colonization within each feature

```{r}
# labels
BinQT <- read.csv("../data/clean/binQT.txt", sep = "\t")
BinQT %>% mutate(feature = paste0(BinLab)) %>%
  mutate(temp = gsub("_.*", "", feature)) %>%
  mutate(label = paste(label, gsub("Don", "", temp), sep = "")) %>%
  select(feature, label)-> BinQT
#
CompFeature(feature_c = "../data/clean/binCover.txt",
           cutoff_pres = 75,
           method = "Assembly",
           mapfile = "../data/clean/mapfile.txt") -> table

fig <- CompFig_pheatmap(table = table,
                 flabel = BinQT)
ggsave("../figs/Bin_pheatmap.pdf", plot = fig, width = 9, height = 11)

```


```{r}
# labels
BinQT <- read.csv("../data/clean/binQT.txt", sep = "\t")
BinQT %>% mutate(feature = paste0(BinLab)) %>%
  mutate(temp = gsub("_.*", "", feature)) %>%
  mutate(label = paste(label, gsub("Don", "", temp), sep = "")) %>%
  select(feature, label)-> BinQT
#
CompFeature(feature_c = "../data/clean/MAGCover.txt",
           cutoff_pres = 75,
           method = "Assembly",
           mapfile = "../data/clean/mapfile.txt") -> table

fig <- CompFig_pheatmap(table = table,
                 flabel = BinQT)
ggsave("../figs/MAG_pheatmap.pdf", plot = fig, width = 9, height = 9)

```

```{r}

tree <- read.tree("../data/clean/MAGs_DonA_and_B.tree")
unique(tree$tip.label) -> ids

# Step 1: Read and filter the data
table <- read.csv("../data/clean/MAGCover.txt", sep = "\t") %>%
  filter(feature %in% ids)

# Step 2: Pivot to wide format for distance calculation
wide_table <- table %>%
  pivot_wider(names_from = feature, values_from = coverage, values_fill = 0) %>%
  column_to_rownames("Sample")

# Step 3: Calculate distance matrix and perform UPGMA clustering
dist_matrix <- dist(wide_table, method = "euclidean")
hc <- hclust(dist_matrix, method = "average")  # UPGMA uses 'average' linkage

# Step 4: Convert to phylo object and plot
tree <- as.phylo(hc)
write.tree(tree, "../data/clean/Samples_DonA_and_B.tree")
plot(tree, main = "UPGMA Tree of Samples", cex = 0.8)



ggplot(table, aes(Sample, feature, fill=coverage)) +
  geom_tile() +
  theme_bw() +
  theme(axis.text = element_blank())

```





```{r}


# Load metadata
BinQT <- read.csv("../data/clean/binQT.txt", sep = "\t")


# Prepare the annotation lines
header <- c(
  "LABELS",
  "SEPARATOR TAB",
  "DATASET_NAME\tSpecies Labels",
  "FIELD_LABELS\tSpecies",
  "FIELD_COLORS\t#ff0000",
  "DATA"
)

# Select and rename columns
tip_labels <- BinQT %>%
  select(BinLab, label) %>%
  rename(tip_id = BinLab, species_label = label)

# Create label lines
label_lines <- paste(tip_labels$tip_id, tip_labels$species_label, sep = "\t")

# Combine header and data
itol_annotation <- c(header, label_lines)

# Write to file
writeLines(itol_annotation, "../data/clean/itol_labels.txt")



```


```{r}

# Read your metadata
BinQT <- read.csv("../data/clean/binQT.txt", sep = "\t")

# Define phylum colors
phylum_col <- c(
  "Firmicutes_A" = "#6a3d9a",
  "Actinobacteriota" = "#33a02c",
  "Bacteroidota" = "#1f78b4",
  "Patescibacteria" = "#ff7f00",
  "Firmicutes" = "#b2df8a",
  "Desulfobacterota" = "#fdbf6f",
  "Firmicutes_B" = "#ffff99",
  "Deferribacterota" = "#a6cee3",
  "Proteobacteria" = "#e31a1c",
  "Campylobacterota" = "#f781bf",
  "NA" = "#808080"
)

# Prepare header
header <- c(
  "DATASET_STYLE",
  "#Style datasets allow the customization of branch and leaf label colors and styles.",
  "SEPARATOR COMMA",
  "DATASET_LABEL,Phylum Label Backgrounds",
  "COLOR,#000000",
  "DATA"
)

# Create style lines for each tip
style_lines <- BinQT %>%
  mutate(bg_color = phylum_col[as.character(Phylum)]) %>%
  mutate(bg_color = ifelse(is.na(bg_color), "#000000", bg_color)) %>%
  mutate(line = paste(BinLab, "label", "node", "#000000", "1", "normal", bg_color, sep = ",")) %>%
  pull(line)

# Combine header and data
itol_style <- c(header, style_lines)

# Write to file
writeLines(itol_style, "../data/clean/itol_phylum_label_backgrounds.txt")


```


```{r}


# Read your metadata
BinQT <- read.csv("../data/clean/binQT.txt", sep = "\t")

# Define phylum colors
phylum_col <- c(
  "Firmicutes_A" = "#6a3d9a",
  "Actinobacteriota" = "#33a02c",
  "Bacteroidota" = "#1f78b4",
  "Patescibacteria" = "#ff7f00",
  "Firmicutes" = "#b2df8a",
  "Desulfobacterota" = "#fdbf6f",
  "Firmicutes_B" = "#ffff99",
  "Deferribacterota" = "#a6cee3",
  "Proteobacteria" = "#e31a1c",
  "Campylobacterota" = "#f781bf",
  "NA" = "#808080"
)

# Prepare header
header <- c(
  "DATASET_STYLE",
  "#Style datasets allow the customization of branch and leaf label colors and styles.",
  "SEPARATOR COMMA",
  "DATASET_LABEL,Phylum Label Backgrounds",
  "COLOR,#000000",
  "DATA"
)

# Create style lines for each tip with uniform font size (e.g., 1.5)
style_lines <- BinQT %>%
  mutate(bg_color = phylum_col[as.character(Phylum)]) %>%
  mutate(bg_color = ifelse(is.na(bg_color), "#000000", bg_color)) %>%
  mutate(line = paste(BinLab, "label", "node", "#000000", "1.5", "normal", bg_color, sep = ",")) %>%
  pull(line)

# Combine header and data
itol_style <- c(header, style_lines)

# Write to file
writeLines(itol_style, "../data/clean/itol_phylum_label_backgrounds_uniform.txt")


```

```{r}


# Read your metadata
BinQT <- read.csv("../data/clean/binQT.txt", sep = "\t")

# Define phylum colors
phylum_col <- c(
  "Firmicutes_A" = "#6a3d9a",
  "Actinobacteriota" = "#33a02c",
  "Bacteroidota" = "#1f78b4",
  "Patescibacteria" = "#ff7f00",
  "Firmicutes" = "#b2df8a",
  "Desulfobacterota" = "#fdbf6f",
  "Firmicutes_B" = "#ffff99",
  "Deferribacterota" = "#a6cee3",
  "Proteobacteria" = "#e31a1c",
  "Campylobacterota" = "#f781bf",
  "NA" = "#808080"
)

# Prepare header
header <- c(
  "DATASET_STYLE",
  "#Style datasets allow the customization of branch and leaf label colors and styles.",
  "SEPARATOR COMMA",
  "DATASET_LABEL,Phylum Branch Colors",
  "COLOR,#000000",
  "DATA"
)

# Create style lines for each tip with branch coloring
style_lines <- BinQT %>%
  mutate(branch_color = phylum_col[as.character(Phylum)]) %>%
  mutate(branch_color = ifelse(is.na(branch_color), "#000000", branch_color)) %>%
  mutate(line = paste(BinLab, "branch", "node", branch_color, "2", "normal", sep = ",")) %>%
  pull(line)

# Combine header and data
itol_branch_style <- c(header, style_lines)

# Write to file
writeLines(itol_branch_style, "../data/clean/itol_phylum_branch_colors.txt")


```

```{r}

BinQT <- read.csv("../data/clean/binQT.txt", sep = "\t")

# Define phylum colors
phylum_col <- c(
  "Firmicutes_A" = "#6a3d9a",
  "Actinobacteriota" = "#33a02c",
  "Bacteroidota" = "#1f78b4",
  "Patescibacteria" = "#ff7f00",
  "Firmicutes" = "#b2df8a",
  "Desulfobacterota" = "#fdbf6f",
  "Firmicutes_B" = "#ffff99",
  "Deferribacterota" = "#a6cee3",
  "Proteobacteria" = "#e31a1c",
  "Campylobacterota" = "#f781bf",
  "NA" = "#808080"
)

# Prepare header for iTOL color strip file
header <- c(
  "DATASET_COLORSTRIP",
  "SEPARATOR COMMA",
  "DATASET_LABEL,Phylum Strip Colors",
  "COLOR,#000000",
  "STRIP_WIDTH,25",
  "MARGIN,5",
  "SHOW_INTERNAL,0",
  "DATA"
)

# Create strip lines for each tip
strip_lines <- BinQT %>%
  mutate(strip_color = phylum_col[as.character(Phylum)]) %>%
  mutate(strip_color = ifelse(is.na(strip_color), "#000000", strip_color)) %>%
  mutate(line = paste(BinLab, strip_color, Phylum, sep = ",")) %>%
  pull(line)

# Combine header and data
itol_strip <- c(header, strip_lines)

# Write to file
writeLines(itol_strip, "../data/clean/itol_phylum_colorstrip.txt")


```




